const tabMots = {
    a: 'Ananas',
    b: 'Banane',
    c: 'Cerise',
    d: 'Datte',
    e: 'Endive',
    f: 'Fraise',
    g: 'Grenade',
    h: 'Haricot',
    i: 'Igname',
    j: 'Jus',
    k: 'Kiwi',
    l: 'Litchi',
    m: 'Mangue',
    n: 'Navet',
    o: 'Orange',
    p: 'Pomme',
    q: 'Quetsche',
    r: 'Radis',
    s: 'Salade',
    t: 'Tomate',
    u: 'Ume',
    v: 'Vanille',
    w: 'Wasabi',
    x: 'X',
    z: 'Zeste de citron',
}

const tabFonctions = {
    a: 'dessinerAnanas',
    b: 'dessinerBanane',
    c: 'dessinerCerise',
    f: 'dessinerFraise',
}
