const tabMots = {
    a: 'Ananas',
    b: 'Banane',
    c: 'Cerise',
    d: 'Datte',
    e: 'Endive',
    f: 'Fraise',
    g: 'Grenade',
    h: 'Haricot',
    i: 'Igname',
    j: 'Jus',
    k: 'Kiwi',
    l: 'Litchi',
    m: 'Mangue',
    n: 'Navet',
    o: 'Orange',
    p: 'Pomme',
    q: 'Quetsche',
    r: 'Radis',
    s: 'Salade',
    t: 'Tomate',
    u: 'Ume',
    v: 'Vanille',
    w: 'Wasabi',
    x: 'Ximenia',
    z: 'Zeste de citron',
}

const tabFonctions = {
    a: 'dessinerAnanas',
    b: 'dessinerBanane',
    c: 'dessinerCerise',
    d: 'dessinerDatte',
    e: 'dessinerEndive',
    f: 'dessinerFraise',
    g: 'dessinerGrenade',
    h: 'dessinerHaricot',
    i: 'dessinerIgname',
    j: 'dessinerJus',
    k: 'dessinerKiwi',
    l: 'dessinerLitchi',
    m: 'dessinerMangue',
    n: 'dessinerNavet',
    o: 'dessinerOrange',
    p: 'dessinerPomme',
    q: 'dessinerQuetsche',
    r: 'dessinerRadis',
    s: 'dessinerSalade',
    t: 'dessinerTomate',
    u: 'dessinerUme',
    v: 'dessinerVanille',
    w: 'dessinerWasabi',
    x: 'dessinerXimenia',
    z: 'dessinerZeste',
}
